#define LOCAL_GAMERULES_ACTION \
	uiScript openMenuOnDvar "ui_gametype" war "settings_quick_war"; \
	uiScript openMenuOnDvar "ui_gametype" sd "settings_quick_sd"; \
	uiScript openMenuOnDvar "ui_gametype" sab "settings_quick_sab"; \
	uiScript openMenuOnDvar "ui_gametype" dm "settings_quick_dm"; \
	uiScript openMenuOnDvar "ui_gametype" dom "settings_quick_dom"; \
	uiScript openMenuOnDvar "ui_gametype" ctf "settings_quick_ctf"; \
    uiScript openMenuOnDvar "ui_gametype" dd "settings_quick_dd"; \
	uiScript openMenuOnDvar "ui_gametype" vip "settings_quick_vip"; \
	uiScript openMenuOnDvar "ui_gametype" gtnw "settings_quick_gtnw"; \
    uiScript openMenuOnDvar "ui_gametype" oneflag "settings_quick_oneflag"; \
	uiScript openMenuOnDvar "ui_gametype" koth "settings_quick_koth";