// Assault Rifles
    #ifdef M4A1
        itemDef
    	{
    		rect -685 65 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "m4" ) )
            exp material ( "weapon_m4carbine" )
    	}
    #endif

    #ifdef FAMAS
        itemDef
    	{
    		rect -540 65 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "famas" ) )
            exp material ( "weapon_famas" )
    	}
    #endif

    #ifdef SCARH
        itemDef
    	{
    		rect -685 115 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "scar" ) )
            exp material ( "weapon_scar_h" )
        }
    #endif

    #ifdef TAR21
        itemDef
    	{
    		rect -540 115 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "tavor" ) )
            exp material ( "weapon_tavor" )
    	}
    #endif

    #ifdef FAL
        itemDef
    	{
    		rect -685 165 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "fal" ) )
            exp material ( "weapon_fnfal" )
        }
    #endif

    #ifdef M16A4
        itemDef
    	{
    		rect -540 165 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "m16" ) )
            exp material ( "weapon_m16a4" )
    	}
    #endif

    #ifdef ACR
        itemDef
    	{
    		rect -685 220 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "masada" ) )
            exp material ( "weapon_masada" )
        }
    #endif

    #ifdef F2000
        itemDef
    	{
    		rect -540 220 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "fn2000" ) )
            exp material ( "weapon_fn2000" )
    	}
    #endif

    #ifdef AK47
        itemDef
    	{
    		rect -685 270 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "ak47" ) )
            exp material ( "weapon_ak47" )
        }
    #endif

    #ifdef AK47C
        itemDef
    	{
    		rect -540 270 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( itemisunlocked( "ak47classic" ) )
            exp material ( "weapon_ak47_classic" )
    	}
    #endif

// Submachine Guns
    #ifdef MP5K
        itemDef
    	{
    		rect -685 65 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "mp5k" ) )
            exp material ( "weapon_mp5k" )
    	}
    #endif

    #ifdef UMP45
        itemDef
    	{
    		rect -540 65 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "ump45" ) )
            exp material ( "weapon_ump45" )
    	}
    #endif

    #ifdef VECTOR
        itemDef
    	{
    		rect -685 115 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "kriss" ) )
            exp material ( "weapon_kriss" )
        }
    #endif

    #ifdef P90
        itemDef
    	{
    		rect -540 115 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "p90" ) )
            exp material ( "weapon_p90" )
    	}
    #endif

    #ifdef UZI
        itemDef
    	{
    		rect -685 165 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "uzi" ) )
            exp material ( "weapon_mini_uzi" )
        }
    #endif

    #ifdef AK74U
        itemDef
    	{
    		rect -540 165 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "ak74u" ) )
            exp material ( "weapon_aks74u" )
    	}
    #endif

    #ifdef PEACEKEEPER
        itemDef
    	{
    		rect -685 220 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "peacekeeper" ) )
            exp material ( "weapon_peacekeeper" )
        }
    #endif
// Light Machine Guns
    #ifdef L86
        itemDef
    	{
    		rect -685 65 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "sa80" ) )
            exp material ( "weapon_sa80" )
    	}
    #endif

    #ifdef RPD
        itemDef
    	{
    		rect -540 65 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "rpd" ) )
            exp material ( "weapon_rpd" )
    	}
    #endif

    #ifdef MG4
        itemDef
    	{
    		rect -685 115 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "mg4" ) )
            exp material ( "weapon_mg4" )
        }
    #endif

    #ifdef AUG
        itemDef
    	{
    		rect -540 115 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "aug" ) )
            exp material ( "weapon_aug" )
    	}
    #endif

    #ifdef M240
        itemDef
    	{
    		rect -685 165 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "m240" ) )
            exp material ( "weapon_m240" )
        }
    #endif
// Sniper Rifles
    #ifdef CHEYTAC
        itemDef
    	{
    		rect -685 65 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "cheytac" ) )
            exp material ( "weapon_cheytac" )
    	}
    #endif

    #ifdef BARRETT
        itemDef
    	{
    		rect -540 65 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "barrett" ) )            
			exp material ( "weapon_barrett50cal" )
    	}
    #endif

    #ifdef WA2000
        itemDef
    	{
    		rect -685 115 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "wa2000" ) )
            exp material ( "weapon_wa2000" )
        }
    #endif

    #ifdef M21
        itemDef
    	{
    		rect -540 115 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "m21" ) )
            exp material ( "weapon_m14ebr" )
    	}
    #endif

    #ifdef M40A3
        itemDef
    	{
    		rect -685 165 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "m40a3" ) )
            exp material ( "weapon_m40a3" )
        }
    #endif

    #ifdef DRAGUNOV
        itemDef
    	{
    		rect -540 165 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "dragunov" ) )
            exp material ( "weapon_dragunov" )
    	}
    #endif

// Machine Pistols
    #ifdef PP2000
        itemDef
    	{
    		rect -685 65 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "pp2000" ) )
            exp material ( "weapon_pp2000" )
    	}
    #endif

    #ifdef GLOCK
        itemDef
    	{
    		rect -540 65 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "glock" ) )
            exp material ( "weapon_glock" )
    	}
    #endif

    #ifdef M93
        itemDef
    	{
    		rect -685 115 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "beretta393" ) )
            exp material ( "weapon_beretta393" )
        }
    #endif

    #ifdef TMP
        itemDef
    	{
    		rect -540 115 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "tmp" ) )
            exp material ( "weapon_tmp" )
    	}
    #endif

// Shotguns
    #ifdef SPAS12
        itemDef
    	{
    		rect -685 65 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "spas12" ) )
            exp material ( "weapon_spas12" )
    	}
    #endif

    #ifdef AA12
        itemDef
    	{
    		rect -540 65 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "aa12" ) )
            exp material ( "weapon_aa12" )
    	}
    #endif

    #ifdef STRIKER
        itemDef
    	{
    		rect -685 115 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "striker" ) )
            exp material ( "weapon_striker" )
        }
    #endif

    #ifdef RANGER
        itemDef
    	{
    		rect -540 115 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "ranger" ) )
            exp material ( "weapon_ranger" )
    	}
    #endif

    #ifdef M1014
        itemDef
    	{
    		rect -685 165 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "m1014" ) )
            exp material ( "weapon_m1014" )
        }
    #endif

    #ifdef MODEL1887
        itemDef
    	{
    		rect -540 165 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "model1887" ) )
            exp material ( "weapon_model1887" )
    	}
    #endif

// Handguns
    #ifdef USP
        itemDef
    	{
    		rect -685 65 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "usp" ) )
            exp material ( "weapon_usp_45" )
    	}
    #endif

    #ifdef MAGNUM
        itemDef
    	{
    		rect -540 65 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "coltanaconda" ) )
            exp material ( "weapon_colt_anaconda" )
    	}
    #endif

    #ifdef M9
        itemDef
    	{
    		rect -685 115 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "beretta" ) )
            exp material ( "weapon_m9beretta" )
        }
    #endif

    #ifdef DEAGLE
        itemDef
    	{
    		rect -540 115 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "deserteagle" ) )
            exp material ( "weapon_desert_eagle" )
    	}
    #endif

    #ifdef DEAGLEGOLD
        itemDef
    	{
    		rect -685 165 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "deserteaglegold" ) )
            exp material ( "weapon_desert_eagle_gold" )
        }
    #endif

// Launchers
    #ifdef AT4
        itemDef
    	{
    		rect -685 65 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "at4" ) )
            exp material ( "weapon_at4" )
    	}
    #endif

    #ifdef THUMPER
        itemDef
    	{
    		rect -540 65 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "m79" ) )
            exp material ( "weapon_m79" )
    	}
    #endif

    #ifdef STINGER
        itemDef
    	{
    		rect -685 115 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "stinger" ) )
            exp material ( "weapon_stinger" )
        }
    #endif

    #ifdef JAVELIN
        itemDef
    	{
    		rect -540 115 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "javelin" ) )
            exp material ( "weapon_javelin" )
    	}
    #endif

    #ifdef RPG
        itemDef
    	{
    		rect -685 165 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "rpg" ) )
            exp material ( "weapon_rpg7" )
        }
    #endif

// Equipment
    #ifdef FRAG
        itemDef
    	{
    		rect -655 65 33.25 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "frag_grenade_mp" ) )
            exp material ( "equipment_frag" )
    	}
    #endif

    #ifdef SEMTEX
        itemDef
    	{
    		rect -510 65 33.25 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "semtex_mp" ) )
            exp material ( "equipment_semtex" )
    	}
    #endif

    #ifdef TKNIFE
        itemDef
    	{
    		rect -655 115 33.25 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "throwingknife_mp" ) )
            exp material ( "equipment_throwing_knife" )
        }
    #endif

    #ifdef TACINSERT
        itemDef
    	{
    		rect -510 115 33.25 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "specialty_tacticalinsertion" ) )
            exp material ( "equipment_flare" )
    	}
    #endif

    #ifdef BLASTSHIELD
        itemDef
    	{
    		rect -655 165 33.25 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "specialty_blastshield" ) )
            exp material ( "equipment_blast_shield" )
        }
    #endif
	
    #ifdef CLAYMORE
        itemDef
    	{
    		rect -510 165 33.25 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "claymore_mp" ) )
            exp material ( "equipment_claymore" )
    	}
    #endif

    #ifdef C4
        itemDef
    	{
    		rect -655 220 33.25 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( isitemunlocked( "c4_mp" ) )
            exp material ( "equipment_c4" )
        }
    #endif

// Special Grenade
    #ifdef FLASH
        itemDef
    	{
    		rect -655 65 33.25 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( 1 )
            exp material ( "weapon_flashbang" )
    	}
    #endif

    #ifdef STUN
        itemDef
    	{
    		rect -510 65 33.25 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( 1 )
            exp material ( "weapon_concgrenade" )
    	}
    #endif

    #ifdef SMOKE
        itemDef
    	{
    		rect -655 115 33.25 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( 1 )
            exp material ( "weapon_smokegrenade" )
        }
    #endif
