// Assault Rifles
    #ifdef M4A1
        itemDef
    	{
    		rect -685 65 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( 1 )
            exp material ( "weapon_m4carbine" )
    	}
    #endif

    #ifdef FAMAS
        itemDef
    	{
    		rect -540 65 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( 1 )
            exp material ( "weapon_famas" )
    	}
    #endif

    #ifdef SCARH
        itemDef
    	{
    		rect -685 115 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( 1 )
            exp material ( "weapon_scar_h" )
        }
    #endif

    #ifdef TAR21
        itemDef
    	{
    		rect -540 115 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( 1 )
            exp material ( "weapon_tavor" )
    	}
    #endif

    #ifdef FAL
        itemDef
    	{
    		rect -685 165 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( 1 )
            exp material ( "weapon_fnfal" )
        }
    #endif

    #ifdef M16A4
        itemDef
    	{
    		rect -540 165 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( 1 )
            exp material ( "weapon_m16a4" )
    	}
    #endif

    #ifdef ACR
        itemDef
    	{
    		rect -685 220 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( 1 )
            exp material ( "weapon_masada" )
        }
    #endif

    #ifdef F2000
        itemDef
    	{
    		rect -540 220 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( 1 )
            exp material ( "weapon_fn2000" )
    	}
    #endif

    #ifdef AK47
        itemDef
    	{
    		rect -685 270 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( 1 )
            exp material ( "weapon_ak47" )
        }
    #endif

    #ifdef AK47C
        itemDef
    	{
    		rect -540 270 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( 1 )
            exp material ( "weapon_ak47_classic" )
    	}
    #endif

// Submachine Guns
    #ifdef MP5K
        itemDef
    	{
    		rect -685 65 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( 1 )
            exp material ( "weapon_mp5k" )
    	}
    #endif

    #ifdef UMP45
        itemDef
    	{
    		rect -540 65 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( 1 )
            exp material ( "weapon_ump45" )
    	}
    #endif

    #ifdef VECTOR
        itemDef
    	{
    		rect -685 115 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( 1 )
            exp material ( "weapon_kriss" )
        }
    #endif

    #ifdef P90
        itemDef
    	{
    		rect -540 115 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( 1 )
            exp material ( "weapon_p90" )
    	}
    #endif

    #ifdef UZI
        itemDef
    	{
    		rect -685 165 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( 1 )
            exp material ( "weapon_mini_uzi" )
        }
    #endif

    #ifdef AK74U
        itemDef
    	{
    		rect -540 165 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( 1 )
            exp material ( "weapon_aks74u" )
    	}
    #endif

    #ifdef PEACEKEEPER
        itemDef
    	{
    		rect -685 220 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( 1 )
            exp material ( "weapon_peacekeeper" )
        }
    #endif
// Light Machine Guns
    #ifdef L86
        itemDef
    	{
    		rect -685 65 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( 1 )
            exp material ( "weapon_sa80" )
    	}
    #endif

    #ifdef RPD
        itemDef
    	{
    		rect -540 65 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( 1 )
            exp material ( "weapon_rpd" )
    	}
    #endif

    #ifdef MG4
        itemDef
    	{
    		rect -685 115 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( 1 )
            exp material ( "weapon_mg4" )
        }
    #endif

    #ifdef AUG
        itemDef
    	{
    		rect -540 115 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( 1 )
            exp material ( "weapon_aug" )
    	}
    #endif

    #ifdef M240
        itemDef
    	{
    		rect -685 165 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( 1 )
            exp material ( "weapon_m240" )
        }
    #endif
// Sniper Rifles
    #ifdef CHEYTAC
        itemDef
    	{
    		rect -685 65 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( 1 )
            exp material ( "weapon_cheytac" )
    	}
    #endif

    #ifdef BARRETT
        itemDef
    	{
    		rect -540 65 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( 1 )
            exp material ( "weapon_barrett50cal" )
    	}
    #endif

    #ifdef WA2000
        itemDef
    	{
    		rect -685 115 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( 1 )
            exp material ( "weapon_wa2000" )
        }
    #endif

    #ifdef M21
        itemDef
    	{
    		rect -540 115 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( 1 )
            exp material ( "weapon_m14ebr" )
    	}
    #endif

    #ifdef M40A3
        itemDef
    	{
    		rect -685 165 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( 1 )
            exp material ( "weapon_m40a3" )
        }
    #endif

    #ifdef DRAGUNOV
        itemDef
    	{
    		rect -540 165 66.5 33.25 3 1
    		decoration
    		visible 1
    		style 3
    		forecolor 1 1 1 1
    		textscale 0.55
    		visible when ( 1 )
            exp material ( "weapon_dragunov" )
    	}
    #endif